name: Update GoDoc

on:
  push:
    tags:
      - 'v*'

jobs:
  update-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger pkg.go.dev update
        run: |
          TAG=${GITHUB_REF##*/}
          curl -sSf https://proxy.golang.org/github.com/byExist/spans/@v/${TAG}.info